{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9a3533c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: face-recognition-models>=0.3.0 in c:\\users\\amal ashok\\anaconda3\\lib\\site-packages (from face_recognition) (0.3.0)\n",
      "Requirement already satisfied: Pillow in c:\\users\\amal ashok\\anaconda3\\lib\\site-packages (from face_recognition) (8.2.0)\n",
      "Requirement already satisfied: Click>=6.0 in c:\\users\\amal ashok\\anaconda3\\lib\\site-packages (from face_recognition) (7.1.2)\n",
      "Collecting dlib>=19.7\n",
      "  Using cached dlib-19.24.0.tar.gz (3.2 MB)\n",
      "Requirement already satisfied: numpy in c:\\users\\amal ashok\\anaconda3\\lib\\site-packages (from face_recognition) (1.20.1)\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib, face-recognition\n",
      "    Running setup.py install for dlib: started\n",
      "    Running setup.py install for dlib: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\AMAL ASHOK\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-wheel-9al5xyq6'\n",
      "       cwd: C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\n",
      "  Complete output (58 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  package init file 'tools\\python\\dlib\\__init__.py' not found (or not a regular file)\n",
      "  running build_ext\n",
      "  Building extension for Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\build\\lib.win-amd64-3.8 -DPYTHON_EXECUTABLE=C:\\Users\\AMAL ASHOK\\anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\build\\lib.win-amd64-3.8 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Error at CMakeLists.txt:5 (message):\n",
      "  \n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "    You must use Visual Studio to build a python extension on windows.  If you\n",
      "    are getting this error it means you have not installed Visual C++.  Note\n",
      "    that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "    development.  You need to install Visual Studio for C++.\n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 222, in <module>\n",
      "      setup(\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 153, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 299, in run\n",
      "      self.run_command('build')\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 134, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 171, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\subprocess.py\", line 364, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\build\\\\lib.win-amd64-3.8', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\AMAL ASHOK\\\\anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\build\\\\lib.win-amd64-3.8', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for dlib\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\AMAL ASHOK\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-record-v4u5fmlu\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\AMAL ASHOK\\anaconda3\\Include\\dlib'\n",
      "         cwd: C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\n",
      "    Complete output (60 lines):\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    package init file 'tools\\python\\dlib\\__init__.py' not found (or not a regular file)\n",
      "    running build_ext\n",
      "    Building extension for Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]\n",
      "    Invoking CMake setup: 'cmake C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\build\\lib.win-amd64-3.8 -DPYTHON_EXECUTABLE=C:\\Users\\AMAL ASHOK\\anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\build\\lib.win-amd64-3.8 -A x64'\n",
      "    -- Building for: NMake Makefiles\n",
      "    CMake Error at CMakeLists.txt:5 (message):\n",
      "    \n",
      "    \n",
      "    \n",
      "      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "    \n",
      "    \n",
      "      You must use Visual Studio to build a python extension on windows.  If you\n",
      "      are getting this error it means you have not installed Visual C++.  Note\n",
      "      that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "      development.  You need to install Visual Studio for C++.\n",
      "    \n",
      "    \n",
      "      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "    \n",
      "    \n",
      "    \n",
      "    \n",
      "    -- Configuring incomplete, errors occurred!\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 222, in <module>\n",
      "        setup(\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\core.py\", line 148, in setup\n",
      "        dist.run_commands()\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\site-packages\\setuptools\\command\\install.py\", line 61, in run\n",
      "        return orig.install.run(self)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\command\\install.py\", line 545, in run\n",
      "        self.run_command('build')\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "        self.run_command(cmd_name)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 134, in run\n",
      "        self.build_extension(ext)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-install-ulys8g1_\\dlib_33c09d8afad4400398b4cd50de20ef3e\\setup.py\", line 171, in build_extension\n",
      "        subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "      File \"C:\\Users\\AMAL ASHOK\\anaconda3\\lib\\subprocess.py\", line 364, in check_call\n",
      "        raise CalledProcessError(retcode, cmd)\n",
      "    subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\build\\\\lib.win-amd64-3.8', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\AMAL ASHOK\\\\anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\build\\\\lib.win-amd64-3.8', '-A', 'x64']' returned non-zero exit status 1.\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\Users\\AMAL ASHOK\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\AMAL ASHOK\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ulys8g1_\\\\dlib_33c09d8afad4400398b4cd50de20ef3e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\AMAL ASHOK\\AppData\\Local\\Temp\\pip-record-v4u5fmlu\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\AMAL ASHOK\\anaconda3\\Include\\dlib' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "!pip install face_recognition\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3147459",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import face_recognition\n",
    "\n",
    "img = cv2.imread(\"Messi1.webp\")\n",
    "rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "img_encoding = face_recognition.face_encodings(rgb_img)[0]\n",
    "\n",
    "img2 = cv2.imread(\"images/Messi.webp\")\n",
    "rgb_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)\n",
    "img_encoding2 = face_recognition.face_encodings(rgb_img2)[0]\n",
    "\n",
    "result = face_recognition.compare_faces([img_encoding], img_encoding2)\n",
    "print(\"Result: \", result)\n",
    "\n",
    "cv2.imshow(\"Img\", img)\n",
    "cv2.imshow(\"Img 2\", img2)\n",
    "cv2.waitKey(0)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
